// Basic Ingredients Message
let basicIngredients = `Oil (olive and sunflower), butter, garlic, onions, oatmeal milk, chickpeas, light coconut cream, rice (jazmin and sushi), beans, lentils, flour, oatmeal, canned corn, canned tuna, soy sauce, arepa flour, pasta (in many ways), cornstarch, spices (truffled salt, garlic powder, cayenne pepper flakes, ground pepper, ground ginger, ground cumin, cumin, curry, oregano, onion flakes, cinnamon, ground cinnamon, ground sweet paprika, ground hot paprika, ground turmeric, chilli ), oyster sauce, wine (white and red), grainy mustard, maple syrup, vanilla flavor, sugar (powdered, brown and white), peanut butter, honey, wine vinegar, vinegar cream, rice vinegar, sesame oil, mirim, chai tea, coffee, wasabi paste, miso paste (white and red), hot sauces, rice papers`;
function popUpBasicIngredients() {
  alert(basicIngredients);
}

let clickHere = document.querySelector(".ingredients-list");
clickHere.addEventListener("click", popUpBasicIngredients);

// Ingredients Avalibles
let ingredientFormElement = document.querySelector("#ingredient-form");
let basicInstructions =
  "Your mission is to ALLWAYS generate a full recepy, make the output in basic HTML form. Please always put a polite line as introduction, a line break, <p><strong><u>Insert here the name of the recepy</u></strong></p>, 2 line breaks, the word '<p><strong>Ingredients:</strong></p>', a line break, the ingredients in bullets <ul><li></li></ul>, 2 line breaks, the word '<p><strong>Instructions:</strong></p>', a line break and all the steps of the recepy in numbers <ul><li></li></ul>. At the  end of the recepy allways sign it as '<h6>- Generated by SheCodes AI</h6>'";

// API integration (IA)
let apiKey = "73050fa355794447f81ab5349190dotd";

let context = `You have a partner and love to cook for both but your always forgot to go to the supermarket. The ingredients from your fride and pantry are: ${basicIngredients}, ${ingredientFormElement}.You can ONLY USE the ingredients from your fride and pantry!. ${basicInstructions}"`;

function generateRecepy(event) {
  event.preventDefault();

  let ingredientsInput =
    ingredientFormElement.querySelector('input[type="text"]').value;

  let prompt = `Please tell me what would you cook (for you and your partner) for lunch, dont make Chickpea, tuna or curry unles that is the only option left.`;
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  let recepyElement = document.querySelector("#recepy");
  recepyElement.classList.remove("hidden");
  recepyElement.innerHTML = `<div class = "loading">🪄 Making magic with what yo have!<div class = "loading">`;

  console.log(`Context: ${context}`);
  console.log(`Prompt: ${prompt}`);

  axios.get(apiUrl).then(displayRecepy);
}

function displayRecepy(response) {
  console.log("Recepy generated");
  magicRecepy = response.data.answer;
  new Typewriter("#recepy", {
    strings: magicRecepy,
    autoStart: true,
    cursor: "",
    delay: 10,
  });
}

ingredientFormElement.addEventListener("submit", generateRecepy);
