// Basic Ingredients Message
let basicIngredients = `Oil (olive and sunflower), butter, garlic, onions, oatmeal milk, chickpeas, light coconut cream, rice (jazmin and sushi), beans, lentils, flour, oatmeal, canned corn, canned tuna, soy sauce, arepa flour, pasta (in many ways), cornstarch, spices (truffled salt, garlic powder, cayenne pepper flakes, ground pepper, ground ginger, ground cumin, cumin, curry, oregano, onion flakes, cinnamon, ground cinnamon, ground sweet paprika, ground hot paprika, ground turmeric, chilli ), oyster sauce, wine (white and red), grainy mustard, maple syrup, vanilla flavor, sugar (powdered, brown and white), peanut butter, honey, wine vinegar, vinegar cream, rice vinegar, sesame oil, mirim, chai tea, coffee, wasabi paste, miso paste (white and red), hot sauces`;
function popUpBasicIngredients() {
  alert(basicIngredients);
}

let clickHere = document.querySelector(".ingredients-list");
clickHere.addEventListener("click", popUpBasicIngredients);

// Ingredients Avalibles
let ingredientFormElement = document.querySelector("#ingredient-form");

// API integration (IA)
let apiKey = "73050fa355794447f81ab5349190dotd";

let basicInstructions =
  "Your mission is to ALLWAYS generate a full recepy. Please always put a polite line as introduction, a line break, the name of the recepy (center, undeline and bold and in the color: #6B8E23), 2 line breaks, the word 'Ingredients' (text align left and underline), a line break, the ingredients in bullets (after each bullet a line break), 2 line breaks, the word 'Instruction' (text align left and underline), a line break and all the steps of the recepy in numbers (after each numbre a line break). At the  end of the recepy, make 3 line breaks and allways sign it as '- Generated by SheCodes AI' inside a (in bold and in color: #FF6347)";

let context =
  "You have a partner and love to cook for both but your always forgot to go to the supermarket. " +
  basicInstructions;

function generateRecepy(event) {
  event.preventDefault();

  let ingredientsInput =
    ingredientFormElement.querySelector('input[type="text"]').value;

  let prompt = `Please tell me what would you cook (for you and your partner) if you ONLY have ${basicIngredients} and ${ingredientFormElement}.`;
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  console.log(`🪄 Making magic with what yo have: ${ingredientsInput}`);
  console.log(`Context: ${context}`);
  console.log(`Prompt: ${prompt}`);

  axios.get(apiUrl).then(displayRecepy);
}

function displayRecepy(response) {
  console.log("Recepy generated");
  magicRecepy = response.data.answer;
  new Typewriter("#recepy", {
    strings: magicRecepy,
    autoStart: true,
    cursor: "",
    delay: 10,
  });
}

ingredientFormElement.addEventListener("submit", generateRecepy);
